name: Node.js Windows integration

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Clone node-nnabt
        uses: actions/checkout@v2
        with:
          path: nnabt-next
      - name: Clone nodejs/node
        uses: actions/checkout@v2
        with:
          repository: nodejs/node
          path: node
      - name: Install deps
        run: choco install nasm
      - name: Replace nnabt in Node.js
        run: |
          rm -Recurse node/tools/nnabt
          cp -Recurse nnabt-next node/tools/nnabt
      - name: Build Node.js
        run: |
          cd node
          ./vcbuild.bat
