name: release-please
on:
  push:
    branches:
      - master
      # todo(gengjiawen) debugging thing
      - feature/changelog
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          package-name: node-gyp
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
