name: Node Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: [10.x, 12.x, 14.x]
        python: [3.6, 3.7, 3.8]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
        env:
          PYTHON_VERSION: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          npm install --no-progress
      - name: Lint with standard
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run lint
      - name: Test with tap (Linux and macOS)
        if: matrix.os != 'windows-latest'
        run: |
          npm test
      - name: Test with tap (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          GYP_MSVS_VERSION=2015 GYP_MSVS_OVERRIDE_PATH="C:\\Dummy" npm test
