# TODO: Line 47, enable pytest --doctest-modules

name: Tests
on: [push, pull_request]
jobs:
  Test:
    strategy:
      fail-fast: false		
      max-parallel: 15
      matrix:
        node: [12.x]
        python: [3.8]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
        env:
          PYTHON_VERSION: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          npm install --no-progress
      - name: Run Node tests
        run: |
          npm test
